### ISSUE TITLE
老哥稳！

### ISSUE THREAD

**Issue by lamppostwell** [TalkUHulk/HulkFakeFace-pytorch#1]

**Comment by TalkUHulk** [comment]
共同学习～

**Comment by zhiplain** [comment]
你好，请问warmup_scheduler这个无法安装啊，没有源啊

**Comment by TalkUHulk** [comment]
> 你好，请问warmup_scheduler这个无法安装啊，没有源啊

 pip install git+https://github.com/ildoonet/pytorch-gradual-warmup-lr.git

**Comment by kkzh2313** [comment]
@TalkUHulk 作者好，请问代码里的chs_stars_features.csv怎么生成的

**Comment by TalkUHulk** [comment]
> 

底库图片抽取的特征

**Comment by kkzh2313** [comment]
@TalkUHulk 有没有这个现成文件麻烦给个下载链接，想今天测试一下看看。明星脸数据集太大要下载好久

**Comment by TalkUHulk** [comment]
> @TalkUHulk 有没有这个现成文件麻烦给个下载链接，想今天测试一下看看。明星脸数据集太大要下载好久

当时只是测试用的，时间久了，没有做备份

**Comment by kkzh2313** [comment]
@TalkUHulk 你好根据readme里明星人脸dataset点进去没发现文件，并不是百度云盘，请问怎么下载
![image](https://user-images.githubusercontent.com/34201133/145350260-48356780-290e-42dc-897d-c20e4b1d6565.png)

**Comment by TalkUHulk** [comment]
> @TalkUHulk 你好根据readme里明星人脸dataset点进去没发现文件，并不是百度云盘，请问怎么下载 ![image](https://user-images.githubusercontent.com/34201133/145350260-48356780-290e-42dc-897d-c20e4b1d6565.png)

似乎是链接失效了。之前我下载过是有效地址。你可以尝试联系网站作者，获取下最新的地址。
