### ISSUE TITLE
what is the different between beauty_epoch_50.pth and beauty_ft_epoch_50.pth

### ISSUE THREAD

**Issue by Usernamezhx** [TalkUHulk/HulkFakeFace-pytorch#2]
HI. thanks for your work first.

**Comment by TalkUHulk** [comment]
Beauty_epoch_50.pth trained by Arcface，and beauty_ft_epoch_50.pth is finetuned with rankloss.

**Comment by Usernamezhx** [comment]
thanks for your reply.
