### ISSUE TITLE
使用自己的数据集进行训练

### ISSUE THREAD

**Issue by hyperion0819** [TalkUHulk/HulkFakeFace-pytorch#3]
您好 我想使用自己的数据集复现这个代码 可以请教一下您 arcface和retinaface的数据集如何摆放 训练步骤是什么吗？

**Comment by TalkUHulk** [comment]
https://github.com/TalkUHulk/HulkFakeFace-pytorch/blob/master/ArcFace/config/config.py

**Comment by TalkUHulk** [comment]
在代码中可以自定义修改：https://github.com/TalkUHulk/HulkFakeFace-pytorch/blob/master/RetinaFace/train.py  parser.add_argument('--training_dataset', default='./widerface/train/label_with_gender.txt', help='Training dataset directory')，
https://github.com/TalkUHulk/HulkFakeFace-pytorch/blob/master/ArcFace/config/config.py；
运行对应文件开始训练：
https://github.com/TalkUHulk/HulkFakeFace-pytorch/blob/master/RetinaFace/train.py
https://github.com/TalkUHulk/HulkFakeFace-pytorch/blob/master/ArcFace/main.py
